### ISSUE TITLE
Suggestion : Permission

### ISSUE THREAD

**Issue by ghost** [Pwn9/PwnPlantGrowth#12]
It might be interesting to add permissions for each plant or group of plants in order to set a different rate for them to be played without this permission : 

Without permission:
WHEAT:
    Growth: 65
    Death: 5
    Biome: []

With permission :
WHEAT:
    Growth: 70
    Death: 1
    Biome: []

Can be added in the configuration a "group like BiomeGroup"

Permission1:
    WHEAT:
        Growth: 70
        Death: 1
        Biome: []

**Comment by msudol** [comment]
Unfortunately due to the way that crops grow, they aren't assigned to a "player" but rather to tick timers in the world when chunks are loaded... so, there is really no way to tie a set of growing crops to any specific player, atleast not in the general sense of the game..  if there are plots or regions that have a player owner it could be done then but that would require another plugin...
